### PR TITLE
Logspout and container level configuration support

### PR DESCRIPTION
**Pull request by brendangibat**
This also adds some AWS instance id injection in to the json object.

### CODE REVIEW

**Comment by brendangibat** [comment]
I also needed to add in some failure cases since I'm relying on docker-compose's always restart setting. In some cases when testing rolling consul as dns, or if it loses consensus then the connection can't recover and it holds indefinitely in a bad connection state.

**Comment by maxekman** [comment]
I think this does a little too much and too specific (to AWS), this adaptor tries to be minimal.. Is there a way you can make this PR fit into that philosophy?

**Comment by brendangibat** [comment]
@maxekman I agree, the AWS item in it breaks being agnostic to infrastructure and would be more appropriate at a logspout module component. I can see what I can do about restructuring what this does.

**Comment by maxekman** [comment]
I'm closing this for now.

**Pull request closed without merging**
